server:
  port: 8888


spring:
  profiles:
    active: local

  application:
    name: config-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      healthcheck:
        enabled: true
    registry-fetch-interval-seconds: 5 # 서비스 목록 5초마다 캐싱(default : 30초)
    disable-delta: true # 캐싱할 때 변경된 부분만 업데이트(default : false)
    # 이를 방지하는 한 가지 방법은 이 속성을 비활성화 하는 것임
    refresh:
      enable: false


management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,busrefresh,info,prometheus,metrics